# Generated by Django 3.2 on 2022-11-23 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_vendor', models.BooleanField(default=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_number', models.CharField(blank=True, max_length=12)),
                ('recipient_code', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='nigeria', max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('premium', models.BooleanField(default=False)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('negative_rating', models.ManyToManyField(blank=True, null=True, related_name='negativeratings', to=settings.AUTH_USER_MODEL)),
                ('rating', models.ManyToManyField(blank=True, null=True, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('daily', 750.0), ('monthly', 15000.0), ('yearly', 70000.0)], default='daily', max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_user', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
