# Generated by Django 4.0.5 on 2022-06-22 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profile_account_number_profile_address_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='negative_rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='negativeratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
